### ISSUE TITLE
dyld missing symbol called when using keccak

### ISSUE THREAD

**Issue by haardikk21** [OffchainLabs/cargo-stylus#139]
Setting up a new Stylus project and using `keccak` somehow is causing a dyld missing symbol resulting in SIGABORT on my machine.

```
rustc 1.83.0 (90b35a623 2024-11-26)
stylus 0.5.8
```

I'm on an Apple Silicon M3 Pro macbook (aarch64). Basic steps to reproduce:

```
# Install dependencies and install cargo stylus
# Then
cargo stylus new counter
```

open up `counter/src/lib.rs` and update the tests like this (just adding one `keccak` line)
```rs
mod test {
    use stylus_sdk::crypto::keccak;

    use super::*;

    #[test]
    fn test_counter() {
        use stylus_sdk::testing::*;
        let vm = TestVM::default();
        let mut contract = Counter::from(&vm);

        let hash = keccak(b"Hello"); // THIS IS THE NEW ADDITION

        assert_eq!(U256::ZERO, contract.number());

        contract.increment();
        assert_eq!(U256::from(1), contract.number());

        contract.add_number(U256::from(3));
        assert_eq!(U256::from(4), contract.number());

        contract.mul_number(U256::from(2));
        assert_eq!(U256::from(8), contract.number());

        contract.set_number(U256::from(100));
        assert_eq!(U256::from(100), contract.number());

        // Override the msg value for future contract method invocations.
        vm.set_value(U256::from(2));

        contract.add_from_msg_value();
        assert_eq!(U256::from(102), contract.number());
    }
}
```

Try running `cargo test --lib` and I get
```
running 1 test
dyld[14077]: missing symbol called
error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `/Users/haardik/Developer/projects/stylus-stuff/counter/target/debug/deps/stylus_hello_world-eacc012058988c8c` (signal: 6, SIGABRT: process abort signal)
```

the same is also true if instead of adding it in tests, you add it to the contract implementation and call that contract function inside your tests

The best guess I have right now is `libstylus` isn't built for `aarch64` on mac silicon but also if that was the case im a bit surprised this is the first issue on that topic? any ideas?

**Comment by rauljordan** [comment]
Hi @haardikk21 try editing your Cargo.toml to this. Replace alloy-primitives with
```toml
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
alloy-primitives = { version = "=0.8.20", features = ["sha3-keccak"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
alloy-primitives = "=0.8.20"
```

My cargo toml looks like this:
```toml
[package]
name = "stylus-hello-world"
version = "0.1.11"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/OffchainLabs/stylus-hello-world"
repository = "https://github.com/OffchainLabs/stylus-hello-world"
keywords = ["arbitrum", "ethereum", "stylus", "alloy"]
description = "Stylus hello world example"

[dependencies]
alloy-primitives = { version = "=0.8.20", features = ["sha3-keccak"] }
alloy-sol-types = "=0.8.20"
mini-alloc = "0.4.2"
stylus-sdk = "0.8.0"
hex = "0.4.3"
dotenv = "0.15.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
alloy-primitives = { version = "=0.8.20", features = ["sha3-keccak"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
alloy-primitives = "=0.8.20"

[dev-dependencies]
tokio = { version = "1.12.0", features = ["full"] }
ethers = "2.0"
eyre = "0.6.8"

[features]
export-abi = ["stylus-sdk/export-abi"]
debug = ["stylus-sdk/debug"]

[[bin]]
name = "stylus-hello-world"
path = "src/main.rs"

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
opt-level = "s"

```
